# https://taskfile.dev

version: '3'


includes:
  devenv: taskfiles/devenv.taskfile.yml
  nix: taskfiles/nix.taskfile.yml

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
